allowBuilds:
  sharp: true
  esbuild: true

overrides:
  fast-uri: ^3.1.6
  js-yaml: ^4.3.2
  colord: ^2.9.4

auditConfig:
  ignoreGhsas:
    - GHSA-w3rx-r6r6-pgpr
    - GHSA-5p2g-fcmc-qvqq
    - GHSA-vwc7-r8mq-g2x9
